# ?? Gradle ??????????????????????
# ?????????? Minecraft ???????
org.gradle.jvmargs=-Xmx3G  
org.gradle.daemon=false     

## ???? ##

# Minecraft ???????? Forge ????
minecraft_version=1.20.1  

# Minecraft ????????????????
minecraft_version_range=[1.20.1,1.21)  

# Forge ???????? Minecraft ????
forge_version=47.4.0  

# Forge ??????
forge_version_range=[47,)  

# Forge Loader ?????????????
loader_version_range=[47,)  

# ??????????? Minecraft ?????
# ????official?parchment ??parchment ????????
mapping_channel=official  

# ?????????
mapping_version=1.20.1    


## Mod ?? ##

# ????????????????????? [a-z][a-z0-9_]{1,63}
# ?????? @Mod("??") ????
mod_id=examplemod

# ???????????????
mod_name=trileaf-monitor-mod

# ????????? https://choosealicense.com/ ?????????
mod_license=All Rights Reserved

# ?????????????????https://semver.org/?
mod_version=1.0.0

# ??? Group ID?????? Maven ??
# ??? Java ????????
mod_group_id=cn.sanyeyun.trileafmonitormod

# ????????????????????
mod_authors=YourNameHere, OtherNameHere

# ???????????\n?
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
